name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run lint checks (flake8)
      run: |
        flake8 app tests --max-line-length=100
    
    - name: Run Black (format check)
      run: black . --check

    - name: Run mypy (type check)
      run: mypy app || true

    - name: Run Bandit (security lint)
      run: bandit -r app

    - name: Copy env file
      run: cp .env.example .env

    - name: Run tests
      env:
        PYTHONPATH: .
      run: |
        pytest tests --disable-warnings -q
    
    - name: Build Docker Image (Test Only)
      run: |
        docker build -t lms-app .